author:
  email: MartyTremblay@users.noreply.github.com
  homepage: https://github.com/MartyTremblay
  name: Marty Tremblay
description: ☢ Airthings Wave component
files:
- custom_components/airthings_wave/__init__.py
- custom_components/airthings_wave/sensor.py
keywords:
- radon
- gas
- airthings
- environmental
- homeassistant
- home-assistant
- custom-component
- python
license: MIT License
name: sensor.airthings_wave
type: component
